version: "3.1"

networks:
  main:

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - main
    container_name: mysql-project-manager
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=project_manager_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3306:3306"

  postgres:
    image: 'postgres:11-alpine'
    networks:
      - main
    container_name: postgres-project-manager
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=project_manager_db
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    networks:
      - main
    container_name: nginx-project-manager
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: docker/php
    networks:
      - main
    container_name: php-project-manager
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php-ini.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  node:
    image: node:10.22-slim
    container_name: node
    networks:
      - main
    ports:
      - 3000:3000
    volumes:
      - .:/application
    working_dir: /application
    tty: true
    stdin_open: true

  #  memcached:
  #    image: memcached:alpine
  #    container_name: project-manager-memcached

  mailhog:
    image: mailhog/mailhog:latest
    networks:
      - main
    container_name: mailhog-project-manager
    ports:
      - "8025:8025"

  redis:
    image: redis:alpine
    networks:
      - main
    ports:
      - 6379:6379
    container_name: redis-project-manager

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
